### PR TITLE
reorganize kminvalues as separate package

### PR DESCRIPTION
**Pull request by jehiah**
This moves kminvalues code into a separate directory with a separate package name so other projects can import that directly

### CODE REVIEW

**Comment by jehiah** [comment]
@mynameisfiber let me know what you think. (I'm not quite using this yet, so might want to hold off on merging for a little while)

**Comment by jehiah** [comment]
@mynameisfiber this is RFM I've successfully used kminvalues as a package directly without the leveldb dependencies based on the work in this pull request.

**Comment by mynameisfiber** [comment]
looks good!  any thoughts about having the kmin library be in a completely separate repo?

**Comment by mynameisfiber** [comment]
@jehiah so there is one error because of a change in functionality.  before, lookups on keys that don't exist resulted in an empty KMV.... this made it so that we can still do complex queries in parsequery even if the key doesn't exist.

One fix is to add something like this in around line 113 in parsequery.go

```
            if result.Data == nil {
                result.Data = kminvalues.NewKMinValues(*defaultSize)
            }
```

Alternatively, this function could be made to exit gracefully if we are trying to fetch data on a key that doesn't exist.  I prefer the former method though since it gives more flexibility in the types of queries you can supply.

**Comment by mynameisfiber** [comment]
Also, is there a nice way to have the dependency on `kminvalues` be relative in the base package rather than linked to github? This makes running the `go test` really annoying.

**Comment by jehiah** [comment]
Unfortunately switching to the full import paths is required in Go 1.1+. I was annoyed when we had to make the switch for nsq, but i've mostly gotten over it. Using [godep](https://github.com/kr/godep) will help, but it's not backwards compatible with 1.0. You can see details of [using godep on nsq](https://github.com/bitly/nsq/pull/266)

It's totally up to you if you want to pull kminvalues into a separate repo. It certainly has some use on it's own. Go import paths do essentially let you treat it that way which is nice.

**Comment by jehiah** [comment]
regarding handling of empty DB's (ie previously unknown keys) i thought i handled that in db.go L123

``` Go
    kmv, err := kminvalues.KMinValuesFromBytes(data)
    if err != nil {
        if len(data) == 0 {
            kmv = kminvalues.NewKMinValues(*defaultSize)
        } else {
            return nil, err
        }
    }
```

I'm not quite following exactly where else i need to add that?

**Comment by mynameisfiber** [comment]
godep looks like it'll work well, but it definitely warrants a makefile to wrap some of that behavior.  Or just require go v1.1+!  That being said, I think this is just more indication that the database and the kmv library should just be in separate repos.

As for the handling of empty sets, adding a hash isn't the only operation you can do with them.  In the `parsequery_test.go`, we take the union of two sets, which goes through the `GetRequest` interface, not the `AddHashRequest` interface (line 75 in db.go).  So maybe, instead of my proposed solution above, you can add similar logic that you added in the `AddHashRequest` to the `GetRequest` so that we always return a valid KMV with and let the error flag indicate whether it was from an actual DB value or not.

**Comment by jehiah** [comment]
@mynameisfiber updated. (FYI: i can't run the full tests because of leveldb dependencies. I'm dreaming of Travis CI setup)

**Comment by mynameisfiber** [comment]
@jehiah awesome... looks great.  I think splitting the DB and the library into two repos and adding travis CI are the next steps.  thanks for the commits!

**Pull request merged**
